apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  labels:
    kubernetes.io/metadata.name: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
  serviceName: mongo-db
  replicas: {{ .values.database.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
    spec:
      containers:
      - name: database
        image: {{ .values.database.image.repository }}:{{ .values.database.image.tag }}
        ports:
        - containerPort: 27017
          name: db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mongo-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mongo-password
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db

  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2